# Generated by Django 5.2 on 2025-05-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('language_flag', models.ImageField(upload_to='language_flags/')),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('pinterest', models.CharField(max_length=100)),
                ('newsletter', models.CharField(max_length=100)),
                ('newsletter_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Ayarlar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='site_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shop_title', models.CharField(max_length=100)),
                ('shop_banner', models.ImageField(upload_to='shop_banner/')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_banner', models.ImageField(upload_to='blog_banner/')),
                ('contact_title', models.CharField(max_length=100)),
                ('contact_banner', models.ImageField(upload_to='contact_banner/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
