# Generated by Django 5.2.3 on 2025-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='language',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='language_flag',
        ),
        migrations.AlterField(
            model_name='setting',
            name='pinterest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
