# Generated by Django 5.2 on 2025-05-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='site_banner',
        ),
    ]
