# Generated by Django 5.2 on 2025-05-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_site_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Parametr', 'verbose_name_plural': 'Parametrlər'},
        ),
    ]
