# Generated by Django 5.2 on 2025-05-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogpage_blogpagetranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Bloq Səhifəsi', 'verbose_name_plural': 'Bloq Səhifələri'},
        ),
        migrations.AlterModelOptions(
            name='blogpagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Bloq Səhifəsi Translation'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Xəbər', 'verbose_name_plural': 'Xəbərlər'},
        ),
        migrations.AlterModelOptions(
            name='newstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Xəbər Translation'},
        ),
        migrations.AlterModelOptions(
            name='searchbyinline',
            options={'verbose_name': 'Axtarış Termini', 'verbose_name_plural': 'Axtarış Terminləri'},
        ),
        migrations.AlterModelOptions(
            name='searchbyinlinetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Axtarış Termini Translation'},
        ),
    ]
