# Generated by Django 5.2 on 2025-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blogpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagetranslation',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_page_images/'),
        ),
    ]
