# Generated by Django 5.2 on 2025-05-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlər'},
        ),
        migrations.AlterModelOptions(
            name='bannertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Banner Translation'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Ana Səhifə', 'verbose_name_plural': 'Ana Səhifələr'},
        ),
        migrations.AlterModelOptions(
            name='homepagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Ana Səhifə Translation'},
        ),
    ]
